# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      echo 'Hello world'
      echo $( pwd ) 
      echo $( ls -R )

- task: DownloadFileshareArtifacts@1
  inputs:
    filesharePath: 'ROOT.war'
    artifactName: 'target'
    downloadPath: '$(System.ArtifactsDirectory)'

#- task: DownloadBuildArtifacts@0
#  inputs:
#    buildType: 'current'
#    downloadType: 'specific'
#    itemPattern: 'target/ROOT.war'
#    downloadPath: '$(System.ArtifactsDirectory)'
#    artifactName: 'target'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'target'
    publishLocation: 'Container'